version: "0.1"
apps:
  acme-docs:
    module: nullstone/aws-s3-cdn
    vars:
      service_count: 2
    connections:
      cluster-namespace:
        block_name: namespace0
    environment:
      TESTING: abc123
      BLAH: blahblahblah
    capabilities:
      - module: nullstone/aws-s3-cdn
        vars:
          enable_www: false
          notfound_behavior:
            document: 404.html
            enabled: true
            spa_mode: false
        connections:
          subdomain:
            block_name: ns-sub-for-acme-docs
        namespace: primary
