version: "0.1"
apps:
  acme-docs:
    module: nullstone/aws-s3-site
    environment:
      TESTING: abc123
      BLAH: blahblahblah
    capabilities:
      - module: nullstone/aws-postgres-access
        vars:
          database_name: "acme-docs"
        connections:
          postgres:
            block_name: postgres
        namespace: primary
