version: "0.1"

events:
  deployments:
    actions:
      - app-deployed
    blocks:
      - acme-api
    targets:
      slack:
        channels:
          - deployments

apps:
  acme-api:
    vars:
      enable_versioned_assets: false
    environment:
      TESTING: abc123
      BLAH: blahblahblah
    capabilities:
      - module: nullstone/aws-s3-cdn
        connections:
          subdomain: ns-sub-for-acme-docs
        namespace: secondary
        vars:
          enable_www: true
